name: CI

on:
  push:
    branches: [ main ]

jobs:
  Deploy-Action:
    name: CI-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: |
        TEMP=$(mktemp)
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $TEMP
        ssh -o 'StrictHostKeyChecking no' -i $TEMP myuser@mysite.com 'bash -s' < scripts/deploy.sh
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_DIGITALOCEAN}}
        username: github
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: cd /var/www/rawpotatochip.com/public && git checkout
